### ISSUE TITLE
Choose a different name for its alternate meaning of "min" method

### ISSUE THREAD

**Issue by sebclara** [smoge/LilyCollider#1]
Hi,
I have a problem in my code when i change computer. The problem come because LilyCollider overwrite a core method min.
You can follow my bad experience here : http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/Timbre-difference-between-linux-and-osx-with-the-same-code-td7617543.html

Thanks,
Sébastien

**Comment by smoge** [comment]
fixed! thanks!
